"""
Advanced Command Handler for Jerico Voice AI Agent
Handles complex commands and system operations
"""

import os
import subprocess
import json
from pathlib import Path
import re

class CommandHandler:
    """Handle advanced command execution"""
    
    COMMAND_PATTERNS = {
        'open_app': r'open\s+(.+)',
        'write_code': r'write\s+(?:a\s+)?(\w+)\s+(?:program|code|script|function)',
        'search_web': r'search\s+(?:for\s+)?(.+?)(?:\s+online)?$',
        'create_file': r'create\s+(?:a\s+)?file\s+(?:called|named)?\s*(.+)',
        'run_command': r'run\s+command\s+(.+)',
        'close_app': r'close\s+(.+)',
        'take_screenshot': r'take\s+(?:a\s+)?screenshot',
        'list_files': r'list\s+(?:files|contents)',
    }
    
    APP_MAPPINGS = {
        'chrome': 'google-chrome',
        'firefox': 'firefox',
        'vs code': 'code',
        'vscode': 'code',
        'code editor': 'code',
        'terminal': 'gnome-terminal',
        'word': 'libreoffice --writer',
        'excel': 'libreoffice --calc',
        'spreadsheet': 'libreoffice --calc',
        'powerpoint': 'libreoffice --impress',
        'calculator': 'gnome-calculator',
        'file manager': 'nautilus',
        'text editor': 'gedit',
    }
    
    WEB_MAPPINGS = {
        'facebook': 'https://facebook.com',
        'youtube': 'https://youtube.com',
        'google': 'https://google.com',
        'github': 'https://github.com',
        'stackoverflow': 'https://stackoverflow.com',
        'twitter': 'https://twitter.com',
        'reddit': 'https://reddit.com',
    }
    
    CODE_TEMPLATES = {
        'python': '''#!/usr/bin/env python3
# Generated by Jerico Voice AI Agent

def main():
    """Main function"""
    print("Hello from Jerico!")

if __name__ == "__main__":
    main()
''',
        'javascript': '''// Generated by Jerico Voice AI Agent

function main() {
    console.log("Hello from Jerico!");
}

main();
''',
        'bash': '''#!/bin/bash
# Generated by Jerico Voice AI Agent

echo "Hello from Jerico!"
''',
        'html': '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generated by Jerico</title>
</head>
<body>
    <h1>Hello from Jerico!</h1>
</body>
</html>
''',
    }
    
    @staticmethod
    def parse_command(user_input):
        """Parse user input and identify command type"""
        for cmd_type, pattern in CommandHandler.COMMAND_PATTERNS.items():
            match = re.search(pattern, user_input, re.IGNORECASE)
            if match:
                return cmd_type, match.groups()
        return None, None
    
    @staticmethod
    def handle_open_app(app_name):
        """Open an application"""
        app_lower = app_name.lower().strip()
        
        # Check if it's a known app
        app_command = CommandHandler.APP_MAPPINGS.get(app_lower, app_name)
        
        try:
            subprocess.Popen(app_command.split())
            return f"Opening {app_name}"
        except Exception as e:
            return f"Could not open {app_name}. Error: {str(e)}"
    
    @staticmethod
    def handle_write_code(language):
        """Generate code template"""
        lang_lower = language.lower().strip()
        
        # Determine file extension
        extensions = {
            'python': '.py',
            'javascript': '.js',
            'bash': '.sh',
            'html': '.html',
        }
        
        template = CommandHandler.CODE_TEMPLATES.get(lang_lower)
        
        if template:
            filename = f"jerico_{language.lower()}{extensions.get(lang_lower, '.txt')}"
            try:
                with open(filename, 'w') as f:
                    f.write(template)
                return f"Created {filename} with {language} template"
            except Exception as e:
                return f"Error creating file: {str(e)}"
        else:
            return f"Code template for {language} not available"
    
    @staticmethod
    def handle_search_web(query):
        """Open search in default browser"""
        import webbrowser
        search_url = f"https://www.google.com/search?q={query.replace(' ', '+')}"
        webbrowser.open(search_url)
        return f"Searching for '{query}' on Google"
    
    @staticmethod
    def handle_create_file(filename, content=""):
        """Create a file with content"""
        try:
            with open(filename, 'w') as f:
                f.write(content)
            return f"Created file: {filename}"
        except Exception as e:
            return f"Error creating file: {str(e)}"
    
    @staticmethod
    def handle_close_app(app_name):
        """Close an application"""
        try:
            subprocess.run(['pkill', '-f', app_name], check=False)
            return f"Closing {app_name}"
        except Exception as e:
            return f"Error closing {app_name}: {str(e)}"
    
    @staticmethod
    def handle_list_files(directory="."):
        """List files in directory"""
        try:
            files = os.listdir(directory)
            file_list = "\n".join(files[:10])  # Limit to first 10
            return f"Files in {directory}:\n{file_list}"
        except Exception as e:
            return f"Error listing files: {str(e)}"
    
    @staticmethod
    def execute(command_type, params):
        """Execute the parsed command"""
        handlers = {
            'open_app': lambda p: CommandHandler.handle_open_app(p[0] if p else 'unknown'),
            'write_code': lambda p: CommandHandler.handle_write_code(p[0] if p else 'python'),
            'search_web': lambda p: CommandHandler.handle_search_web(p[0] if p else 'jerico'),
            'create_file': lambda p: CommandHandler.handle_create_file(p[0] if p else 'jerico_file.txt'),
            'close_app': lambda p: CommandHandler.handle_close_app(p[0] if p else 'unknown'),
            'list_files': lambda p: CommandHandler.handle_list_files(p[0] if p else '.'),
            'take_screenshot': lambda p: CommandHandler.take_screenshot(),
        }
        
        handler = handlers.get(command_type)
        if handler:
            return handler(params)
        return "Command not recognized"
    
    @staticmethod
    def take_screenshot():
        """Take a screenshot"""
        try:
            from PIL import ImageGrab
            screenshot = ImageGrab.grab()
            filename = "jerico_screenshot.png"
            screenshot.save(filename)
            return f"Screenshot saved as {filename}"
        except ImportError:
            return "Screenshot functionality requires Pillow. Install with: pip install Pillow"
        except Exception as e:
            return f"Error taking screenshot: {str(e)}"


# Bengali command mappings for enhanced language support
BENGALI_COMMANDS = {
    'খুলো': 'open',
    'বন্ধ করো': 'close',
    'তৈরি করো': 'create',
    'লেখো': 'write',
    'অনুসন্ধান': 'search',
    'ফাইল': 'file',
    'প্রোগ্রাম': 'program',
    'কোড': 'code',
    'স্ক্রিনশট': 'screenshot',
}

def translate_bengali_command(bangla_text):
    """Translate Bengali commands to English"""
    english_text = bangla_text.lower()
    
    for bengali_word, english_word in BENGALI_COMMANDS.items():
        english_text = english_text.replace(bengali_word, english_word)
    
    return english_text
